 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    -QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   2.036E-10  4.176E+02  1.228E+04  0.000E+00 -6.567E+03  0.000E+00  0.000E+00 -2.687E+04  1.718E+04  0.000E+00  4.389E+03  0.000E+00
 Energy balance for sum of all zone
   0       0.00   2.036E-10  4.176E+02  1.228E+04  0.000E+00 -6.567E+03  0.000E+00  0.000E+00 -2.687E+04  1.718E+04  0.000E+00  4.389E+03  0.000E+00
