 Energy balance per zone
 
  Zonenr Rel_BAL  BAL_ENERGY= -DQAIRdt  +QHEAT     -QCOOL    +QINF      +QVENT       +QCOUPL    -QTRANS  +QGAININT  +QWGAIN    +QSOLGAIN  +QSOLAIR
   -     %        kJ          kJ         kJ          kJ         kJ         kJ         kJ          kJ         kJ         kJ         kJ         kJ
   1       0.00   1.604E-10  5.952E+02  0.000E+00  0.000E+00 -1.582E+03  0.000E+00  0.000E+00 -1.075E+04  1.162E+04  0.000E+00  1.304E+03  0.000E+00
 Energy balance for sum of all zone
   0       0.00   1.604E-10  5.952E+02  0.000E+00  0.000E+00 -1.582E+03  0.000E+00  0.000E+00 -1.075E+04  1.162E+04  0.000E+00  1.304E+03  0.000E+00
